apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.appName }}-postgres {{ .Values.postgres.service.port | default 5432 }}; do
                echo "Waiting for Postgres..."
                sleep 2
              done
              echo "Postgres is up!"
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-secrets
                  key: jwtKey
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.env.db }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.env.user }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-secrets
                  key: dbPassword
            - name: POSTGRES_HOST
              value: "{{ .Values.appName }}-postgres"
            - name: DATABASE_PORT
              value: "{{ .Values.postgres.service.port | default 5432 }}"
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appName }}-ports
                  key: BACKEND_PORT
            - name: APP_HOST
              value: "0.0.0.0"

          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 25
            periodSeconds: 50
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 25
            periodSeconds: 50