apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwtKey: {{ .Values.backend.env.jwtKey }}
  secretKey: {{ .Values.frontend.env.secretKey }}
  dbPassword: {{ .Values.postgres.env.password  }}