apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  jwtKey: {{ .Values.backend.env.jwtKey | b64enc }}
  secretKey: {{ .Values.frontend.env.secretKey | b64enc }}
  dbPassword: {{ .Values.postgres.env.password | b64enc }}