{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: {{ .Values.appName }}-postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
{{- end }}